requires 'REST::Client';
requires 'Test::Simple';
requires 'Moose';
requires 'Readonly';
requires 'Set::Scalar';
requires 'List::Util';
requires 'Mojo::JSON';
requires 'JSON::XS';
requires 'Data::Structure::Util';
