=encoding utf8

=pod

=head1 방법 1 ( solution1.pl )

 각 엘리베이터의 상태를 확인하며 Command 를 결정한다.

 엘리베이터의 최초 상태는 STOPPED 이며, 새롭게 발생한 
 Call 에 의해 움직이기 시작한다.

 호출된 엘리베이터는 다른 Call 이 발생하더라도 무시하고 자신을 
 호출한 Call 의 층으로 이동한다.

 Call 을 태우고 Call 의 목적 방향으로 이동하며, 다른 Call 중 
 방향이 같은 Call 을 탑승시킨다. 

 첫 Call 을 탑승시킨 엘리베이터는 한 방향으로만 이동하며
 모든 승객이 내리면 다시 STOPPED 상태가 된다.

=over 4 결과 ( timestamp )

=item * problem0 - 16

=item * problem1 - 588

=item * problem2 - 1886

=back

=cut
